# Generated by Django 4.0.2 on 2024-01-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0002_portfolio_assetrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrecord',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
