# Generated by Django 4.0.2 on 2024-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0003_assetrecord_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash',
            field=models.JSONField(default=dict),
        ),
    ]
