# Generated by Django 4.0.2 on 2024-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0004_portfolio_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='NancyPelosi Tracker bwahaha', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='now_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
