# Generated by Django 4.0.2 on 2024-01-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0005_portfolio_name_alter_portfolio_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='cash',
            new_name='data',
        ),
        migrations.DeleteModel(
            name='AssetRecord',
        ),
    ]
