# Generated by Django 4.0.2 on 2024-01-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0007_portfolio_capital_alter_portfolio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
