# Generated by Django 4.0.2 on 2024-01-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0010_rename_capital_portfolio_initial_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='advice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(),
        ),
    ]
