# Generated by Django 4.0.2 on 2024-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0011_portfolio_advice_alter_portfolio_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='advice',
            field=models.CharField(blank=True, default='sample', max_length=100),
        ),
    ]
