# Generated by Django 4.0.2 on 2024-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0012_alter_portfolio_advice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='advice',
        ),
    ]
