# Generated by Django 4.0.2 on 2024-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0013_remove_portfolio_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
