# Generated by Django 4.0.2 on 2024-01-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0016_alter_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='advice',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
