# Generated by Django 4.0.2 on 2024-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0018_alter_portfolio_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
