# Generated by Django 4.0.2 on 2024-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0019_portfolio_current_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='news',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
