# Generated by Django 5.0.1 on 2024-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0020_portfolio_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
