# Generated by Django 5.0.1 on 2024-01-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrograde', '0022_alter_portfolio_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='news',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
